version: "3.8"
services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "3000:3000"
    depends_on:
      - db-service
    environment:
      - DATABASE_URL=postgresql://admin:secret@db-service:5432/user_management

  db-service:
    build:
      context: ./db-service
    ports:
      - "5432:5432"
